# Site wide configuration

title: А хотите, я расскажу вам...
description:
logo: stru_clean.png
teaser: default-teaser-400x250.jpg
locale: ru_RU
#url: http://localhost:4000
url: http://barancev.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Алексей Баранцев
  email: barancev@gmail.com
  twitter: barancev
  google:
    ad-client: 
    ad-slot: 
  bio: Если вам понравилась эта статья, вы можете поделиться ею в социальных сетях (кнопочки ниже), а потом <a href="http://barancev.github.io">вернуться на главную страницу блога и почитать другие мои статьи</a>.<br/>Ну а если вы не согласны с чем-то или хотите что-нибудь дополнить &ndash; оставьте комментарий ниже, может быть это послужит поводом для написания новой интересной статьи.
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: barancev


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
